# Site settings
title: becomedragon's blog
motto: Talk is cheap，show me the blog ^ ^
email: becomedragon@me.com
description: this is a blog record me . but public for you. 
baseurl: "http://becomedragon.github.io" # the subpath of your site, e.g. /blog/
url: "http://becomedragon.github.io" # the base hostname & protocol for your site
twitter_username: becomedragon
github_username:  becomedragon

# Build settings
markdown: kramdown
